version: '3'

services:
  akka-collaborator:
    image: akkacollaborator
    build:
      context: ./AkkaCollaborator
      dockerfile: Dockerfile

  akka-seed:
    image: akkaseed
    build:
      context: ./AkkaSeed
      dockerfile: Dockerfile
